language : generic
branches:
 only:
   - master

sudo: required

services:
 -docker

before_install:
 - docker build -t songyoungmin/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
 - docker run -e CI=true songyoungmin/react-test-app npm run test
 

after_success:
  - docker build -t songyoungmin/docker-frontend ./frontend
  - docker build -t songyoungmin/docker-backend  ./backend
  - docker build -t songyoungmin/docker-nginx ./nginx

  - echo "$PASSWORD" | docker login -u "$USER" --password-stdin

  - docker push songyoungmin/docker-frontend
  - docker push songyoungmin/docker-backend
  - docker push songyoungmin/docker-nginx

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-fullstack-app"
 env: "Dockerfullstackapp-env"
 bucket_name : elasticbeanstalk-us-east-2-529541061065
 bucket_path :"docker-fullstack-app"
 on:
   branch: master

access_key_id: $AWS_ACCESS_KEY
security_access_key: $AWS_SECRET_ACCESS_KEY









